[package]
name = "rawtalk"
version = "0.1.0"
authors = ["dy9-spec <di.yao.think@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.47.0"
rusoto_credential = "0.47.0"
tokio = "1.8.1"
